# Description
# This configuration is written for switches Lonsonho
#  - Quick press (from 20 ms to 1 s) on any key turns on/off the relevant relay
#  - Long press (from 2 to 4 seconds) on any key locks/unlocks all keys
#  - Long press (at least 10 seconds) on all keys will restart the chip
#
# https://github.com/xxsokolov/esphome/blob/main/switches/lonsonho.yaml
#
# 
# example
#
#substitutions:
#    device_name: lonsonho-x802a-lg-bedroom-1
#    name: "Lonsonho Switch Bedroom 1"
#    ota_pass: "your_ota_pass"
#    wifi_ssid: "your_wifi"
#    wifi_pass: "your_wifi_pass"
#    ap_pass: "your_ap_pass"
#    api_pass: "your_api_pass"
#    logging: INFO
#    
#    light_restore_mode: RESTORE_DEFAULT_OFF
#    
#packages:
#  lonsonho:
#    url: https://github.com/xxsokolov/esphome
#    ref: main
#    files:
#      - switches/lonsonho.yaml
#   refresh: 0s


esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

logger:
  level: ${logging}

ota:
  password: ${ota_pass}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  fast_connect: on
  ap:
    ssid: ${device_name}
    password: ${ap_pass}

api:
  password: ${api_pass}
  reboot_timeout: 1h
    
output:
  - platform: gpio
    pin: GPIO12
    id: output_one_relay
    
  - platform: gpio
    pin: GPIO14
    id: output_two_relay
    
  - platform: gpio
    id: output_led_green  
    pin: 
      number: GPIO13
      mode: OUTPUT
      inverted: true 
      
light:
  - platform: binary
    name: "${name} Left Button"
    id: one_relay
    output: output_one_relay
    restore_mode: ${light_restore_mode}

  - platform: binary
    name: "${name} Right Button"
    id: two_relay
    output: output_two_relay
    restore_mode: ${light_restore_mode}

  - platform: status_led
    id: status_green_led
    internal: true
    pin: 
      number: GPIO13
      mode: OUTPUT
      inverted: true 
      
binary_sensor:
  - platform: gpio
    name: "${name} Pressed Left Button"  
    id: one_button    
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
    filters:
      - invert:
      - delayed_on: 20ms
    on_multi_click:
      - timing:
        - ON for 20ms to 1s
        - OFF for at least 100ms
        then:
          - logger.log: "Single Short Clicked One Button"
          - if:
              condition:
                - switch.is_off: buttons_lock
              then:
                - if:
                    condition:
                      - light.is_off: one_relay
                    then:
                      - light.turn_on: one_relay
                    else:
                      - light.turn_off: one_relay
              else:
                - output.turn_off: output_led_green
                - delay: 100ms              
                - output.turn_on: output_led_green
                - delay: 200ms
                - output.turn_off: output_led_green
                - delay: 100ms              
                - output.turn_on: output_led_green
                - delay: 200ms
                - output.turn_off: output_led_green              
                - delay: 100ms      
                - if:
                    condition:
                      - switch.is_on: backlighting
                    then:
                      - output.turn_on: output_led_green
      - timing:
        - ON for 2s to 4s
        - OFF for at least 100ms
        then:
          - logger.log: "Single Long Clicked One Button"
          - if:
              condition:
                - binary_sensor.is_off: two_button
              then:
                - if:
                    condition:
                      - switch.is_off: buttons_lock
                    then:
                      - switch.turn_on: buttons_lock
                      - output.turn_off: output_led_green                
                      - delay: 500ms
                      - output.turn_on: output_led_green               
                      - delay: 1000ms
                      - output.turn_off: output_led_green                      
                    else:
                      - output.turn_off: output_led_green                
                      - delay: 500ms
                      - output.turn_on: output_led_green               
                      - delay: 1000ms
                      - output.turn_off: output_led_green
                      - if:
                          condition:
                            - switch.is_on: backlighting
                          then:
                            - output.turn_on: output_led_green
                      - switch.turn_off: buttons_lock
              else:
                - if:
                    condition:
                      - switch.is_off: buttons_lock
                    then:
                      - binary_sensor.template.publish:
                          id: pressed_two_buttons
                          state: true
                      - binary_sensor.template.publish:
                          id: pressed_two_buttons
                          state: false
                    else:
                      - output.turn_off: output_led_green
                      - delay: 100ms              
                      - output.turn_on: output_led_green
                      - delay: 200ms
                      - output.turn_off: output_led_green
                      - delay: 100ms              
                      - output.turn_on: output_led_green
                      - delay: 200ms
                      - output.turn_off: output_led_green              
                      - delay: 100ms      
                      - if:
                          condition:
                            - switch.is_on: backlighting
                          then:
                            - output.turn_on: output_led_green
      - timing:
        - ON for at least 10s
        then:
          - logger.log: "Reboot"
          - if:
              condition:
                - switch.is_off: buttons_lock
              then:
                - if:
                    condition:
                      - binary_sensor.is_on: two_button
                    then:
                      - output.turn_off: output_led_green                
                      - delay: 500ms
                      - output.turn_on: output_led_green               
                      - delay: 1000ms  
                      - binary_sensor.turn_off: one_button
                      - binary_sensor.turn_off: two_button
                      - delay: 1000ms
                      - button.press: restart_button
                    else:
                      - output.turn_off: output_led_green
                      - delay: 100ms              
                      - output.turn_on: output_led_green
                      - delay: 300ms
                      - output.turn_off: output_led_green
                      - delay: 100ms              
                      - output.turn_on: output_led_green
                      - delay: 300ms
                      - output.turn_off: output_led_green              
                      - delay: 100ms
                      - if:
                          condition:
                            - switch.is_on: backlighting
                          then:
                            - output.turn_on: output_led_green
              else:
                - output.turn_off: output_led_green
                - delay: 100ms              
                - output.turn_on: output_led_green
                - delay: 200ms
                - output.turn_off: output_led_green
                - delay: 100ms              
                - output.turn_on: output_led_green
                - delay: 200ms
                - output.turn_off: output_led_green              
                - delay: 100ms      
                - if:
                    condition:
                      - switch.is_on: backlighting
                    then:
                      - output.turn_on: output_led_green

  - platform: gpio
    name: "${name} Pressed Right Button"  
    id: two_button    
    pin: 
      number: RX
      mode: INPUT_PULLUP
    filters:
      - invert:
      - delayed_on: 20ms
    on_multi_click:
      - timing:
        - ON for 20ms to 1s
        - OFF for at least 100ms
        then:
          - logger.log: "Single Short Clicked Two Button"
          - if:
              condition:
                - switch.is_off: buttons_lock
              then:
                - if:
                    condition:
                      - light.is_off: two_relay
                    then:
                      - light.turn_on: two_relay
                    else:
                      - light.turn_off: two_relay
              else:
                - output.turn_off: output_led_green
                - delay: 100ms              
                - output.turn_on: output_led_green
                - delay: 200ms
                - output.turn_off: output_led_green
                - delay: 100ms              
                - output.turn_on: output_led_green
                - delay: 200ms
                - output.turn_off: output_led_green              
                - delay: 100ms              
                - if:
                    condition:
                      - switch.is_on: backlighting
                    then:
                      - output.turn_on: output_led_green
      - timing:
        - ON for 2s to 4s
        - OFF for at least 100ms
        then:
          - logger.log: "Single Long Clicked Two Button"
          - if:
              condition:
                - binary_sensor.is_off: one_button
              then:
                - if:
                    condition:
                      - switch.is_off: buttons_lock
                    then:
                      - switch.turn_on: buttons_lock
                      - output.turn_off: output_led_green                
                      - delay: 500ms
                      - output.turn_on: output_led_green               
                      - delay: 1000ms
                      - output.turn_off: output_led_green
                      - if:
                          condition:
                            - switch.is_on: backlighting
                          then:
                            - output.turn_on: output_led_green
                    else:
                      - output.turn_off: output_led_green                
                      - delay: 500ms
                      - output.turn_on: output_led_green               
                      - delay: 1000ms
                      - output.turn_off: output_led_green
                      - if:
                          condition:
                            - switch.is_on: backlighting
                          then:
                            - output.turn_on: output_led_green
                      - switch.turn_off: buttons_lock             
              else:
                - if:
                    condition:
                      - switch.is_off: buttons_lock
                    then:
                      - binary_sensor.template.publish:
                          id: pressed_two_buttons
                          state: true
                      - binary_sensor.template.publish:
                          id: pressed_two_buttons
                          state: false
                    else:
                      - output.turn_off: output_led_green
                      - delay: 100ms              
                      - output.turn_on: output_led_green
                      - delay: 200ms
                      - output.turn_off: output_led_green
                      - delay: 100ms              
                      - output.turn_on: output_led_green
                      - delay: 200ms
                      - output.turn_off: output_led_green              
                      - delay: 100ms      
                      - if:
                          condition:
                            - switch.is_on: backlighting
                          then:
                            - output.turn_on: output_led_green

  - platform: template
    name: "${name} Pressed Two Buttons"  
    id: pressed_two_buttons

switch:
  - platform: template
    name: "${name} Backlighting"
    id: backlighting
    icon: "mdi:weather-night"
    optimistic: true
    on_turn_on:
      - output.turn_on: output_led_green
    on_turn_off:
      - output.turn_off: output_led_green

  - platform: template
    name: "${name} Buttons Lock"
    id: buttons_lock
    icon: "mdi:lock"
    optimistic: true
    restore_state: true

button:
  - platform: restart
    id: restart_button
    name: "${name} Restart"

sensor:  
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
