substitutions:
    device_name: lonsonho-x802a-lg-kitchen-1
    name: "Lonsonho Switch Kitchen 1"
    ota_pass: "your_ota_pass"
    wifi_ssid: "your_wifi"
    wifi_pass: "your_wifi_pass"
    ap_pass: "your_ap_pass"
    api_pass: "your_api_pass"
    logging: INFO
    
    light_restore_mode: RESTORE_DEFAULT_OFF
    
packages:
  lonsonho:
    url: https://github.com/xxsokolov/esphome
    ref: main
    files:
      - switches/lonsonho.yaml
    refresh: 0s
