# Description
# This configuration is written for switches Zemismart
# - Quick press (from 20 ms to 1 s) on the key turns on/off the relay
# - Long press (for 2s to 4s) on the key locks/unlocks the keys
# - Long press (at least 10 seconds) on the key will restart the chip
# https://github.com/xxsokolov/esphome/blob/main/switches/zemismart
# 
# example
#
#substitutions:
#    device_name: zemismart-wn-ln1e-bathroom-1
#    name: "Zemismart WN LN1E Bathroom 1"
#    ota_pass: "your_ota_pass"
#    wifi_ssid: "your_wifi"
#    wifi_pass: "your_wifi_pass"
#    ap_pass: "your_ap_pass"
#    api_pass: "your_api_pass"
#    logging: INFO
#    
#    light_restore_mode: RESTORE_DEFAULT_OFF
#    
#packages:
#  lonsonho:
#    url: https://github.com/xxsokolov/esphome
#    ref: main
#    files:
#      - switches/zemismart-wn-ln1e.yaml
#   refresh: 0s

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

logger:
  level: ${logging}

ota:
  password: ${ota_pass}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  fast_connect: on
  ap:
    ssid: ${device_name}
    password: ${ap_pass}

api:
  password: ${api_pass}
  reboot_timeout: 1h    
    
    
output:
  - platform: gpio
    pin: GPIO13
    id: output_one_relay
    
  - platform: gpio
    id: output_relay_led  
    pin: 
      number: GPIO15
      mode: OUTPUT
      inverted: True
          
light:
  - platform: binary
    name: "${name} One Button"
    id: one_relay
    output: output_one_relay
    restore_mode: ${light_restore_mode}
    on_turn_on:
      - output.turn_on: output_relay_led
    on_turn_off:
      - output.turn_off: output_relay_led

  - platform: status_led
    id: status_green_led
    internal: true
    pin: 
      number: GPIO2
      mode: OUTPUT
      inverted: true 

binary_sensor:
  - platform: gpio
    name: "${name} Pressed One Button"  
    id: one_button  
    pin:
      number: GPIO16
      mode: INPUT
    filters:
      - invert:
      - delayed_on: 20ms
    on_multi_click:
      - timing:
        - ON for 20ms to 1s
        - OFF for at least 100ms
        then:
          - logger.log: "Single Short Clicked One Button"
          - if:
              condition:
                - switch.is_off: buttons_lock
              then:
                - if:
                    condition:
                      - light.is_off: one_relay
                    then:
                      - light.turn_on: one_relay
                      - output.turn_on: output_relay_led
                    else:
                      - light.turn_off: one_relay
                      - output.turn_off: output_relay_led
              else:
                - output.turn_off: output_relay_led
                - delay: 100ms              
                - output.turn_on: output_relay_led
                - delay: 200ms
                - output.turn_off: output_relay_led
                - delay: 100ms              
                - output.turn_on: output_relay_led
                - delay: 200ms
                - output.turn_off: output_relay_led              
                - delay: 100ms      
                - if:
                    condition:
                      - light.is_on: one_relay
                    then:
                      - output.turn_on: output_relay_led
      - timing:
        - ON for 2s to 4s
        - OFF for at least 100ms
        then:
          - logger.log: "Single Long Clicked One Button"
          - if:
              condition:
                - switch.is_off: buttons_lock
              then:
                - switch.turn_on: buttons_lock
                - output.turn_off: output_relay_led                
                - delay: 500ms
                - output.turn_on: output_relay_led               
                - delay: 1000ms
                - output.turn_off: output_relay_led
                - if:
                    condition:
                      - light.is_on: one_relay
                    then:
                      - output.turn_on: output_relay_led
              else:
                - output.turn_off: output_relay_led                
                - delay: 500ms
                - output.turn_on: output_relay_led               
                - delay: 1000ms
                - output.turn_off: output_relay_led
                - if:
                    condition:
                      - light.is_on: one_relay
                    then:
                      - output.turn_on: output_relay_led
                - switch.turn_off: buttons_lock
      - timing:
        - ON for at least 10s
        then:
          - logger.log: "Reboot"
          - if:
              condition:
                - switch.is_off: buttons_lock
              then:
                - button.press: restart_button
              else:
                - output.turn_off: output_relay_led                
                - delay: 500ms
                - output.turn_on: output_relay_led               
                - delay: 1000ms
                - output.turn_off: output_relay_led
                - if:
                    condition:
                      - light.is_on: one_relay
                    then:
                      - output.turn_on: output_relay_led

switch:
  - platform: template
    name: "${name} Buttons Lock"
    id: buttons_lock
    icon: "mdi:lock"
    optimistic: true
    restore_state: true

button:
  - platform: restart
    id: restart_button
    name: "${name} Restart"

sensor:  
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
